// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package com.msg_gRPC.grpc;

public interface ConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gRPC.Confirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool reussite = 1;</code>
   */
  boolean getReussite();

  /**
   * <code>string message_erreur = 2;</code>
   */
  java.lang.String getMessageErreur();
  /**
   * <code>string message_erreur = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageErreurBytes();
}
