// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package com.msg_gRPC.grpc;

/**
 * Protobuf type {@code gRPC.Message}
 */
public  final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gRPC.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    expediteur_ = "";
    destinataire_ = "";
    contenu_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            expediteur_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            destinataire_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            contenu_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.msg_gRPC.grpc.Messaging.internal_static_gRPC_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.msg_gRPC.grpc.Messaging.internal_static_gRPC_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.msg_gRPC.grpc.Message.class, com.msg_gRPC.grpc.Message.Builder.class);
  }

  public static final int EXPEDITEUR_FIELD_NUMBER = 1;
  private volatile java.lang.Object expediteur_;
  /**
   * <code>string expediteur = 1;</code>
   */
  public java.lang.String getExpediteur() {
    java.lang.Object ref = expediteur_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      expediteur_ = s;
      return s;
    }
  }
  /**
   * <code>string expediteur = 1;</code>
   */
  public com.google.protobuf.ByteString
      getExpediteurBytes() {
    java.lang.Object ref = expediteur_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      expediteur_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATAIRE_FIELD_NUMBER = 2;
  private volatile java.lang.Object destinataire_;
  /**
   * <code>string destinataire = 2;</code>
   */
  public java.lang.String getDestinataire() {
    java.lang.Object ref = destinataire_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinataire_ = s;
      return s;
    }
  }
  /**
   * <code>string destinataire = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDestinataireBytes() {
    java.lang.Object ref = destinataire_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinataire_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENU_FIELD_NUMBER = 3;
  private volatile java.lang.Object contenu_;
  /**
   * <code>string contenu = 3;</code>
   */
  public java.lang.String getContenu() {
    java.lang.Object ref = contenu_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contenu_ = s;
      return s;
    }
  }
  /**
   * <code>string contenu = 3;</code>
   */
  public com.google.protobuf.ByteString
      getContenuBytes() {
    java.lang.Object ref = contenu_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contenu_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getExpediteurBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, expediteur_);
    }
    if (!getDestinataireBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, destinataire_);
    }
    if (!getContenuBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, contenu_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getExpediteurBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, expediteur_);
    }
    if (!getDestinataireBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, destinataire_);
    }
    if (!getContenuBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, contenu_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.msg_gRPC.grpc.Message)) {
      return super.equals(obj);
    }
    com.msg_gRPC.grpc.Message other = (com.msg_gRPC.grpc.Message) obj;

    boolean result = true;
    result = result && getExpediteur()
        .equals(other.getExpediteur());
    result = result && getDestinataire()
        .equals(other.getDestinataire());
    result = result && getContenu()
        .equals(other.getContenu());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXPEDITEUR_FIELD_NUMBER;
    hash = (53 * hash) + getExpediteur().hashCode();
    hash = (37 * hash) + DESTINATAIRE_FIELD_NUMBER;
    hash = (53 * hash) + getDestinataire().hashCode();
    hash = (37 * hash) + CONTENU_FIELD_NUMBER;
    hash = (53 * hash) + getContenu().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.msg_gRPC.grpc.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg_gRPC.grpc.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg_gRPC.grpc.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg_gRPC.grpc.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg_gRPC.grpc.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg_gRPC.grpc.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg_gRPC.grpc.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.msg_gRPC.grpc.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msg_gRPC.grpc.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.msg_gRPC.grpc.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msg_gRPC.grpc.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.msg_gRPC.grpc.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.msg_gRPC.grpc.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gRPC.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gRPC.Message)
      com.msg_gRPC.grpc.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.msg_gRPC.grpc.Messaging.internal_static_gRPC_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.msg_gRPC.grpc.Messaging.internal_static_gRPC_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.msg_gRPC.grpc.Message.class, com.msg_gRPC.grpc.Message.Builder.class);
    }

    // Construct using com.msg_gRPC.grpc.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      expediteur_ = "";

      destinataire_ = "";

      contenu_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.msg_gRPC.grpc.Messaging.internal_static_gRPC_Message_descriptor;
    }

    @java.lang.Override
    public com.msg_gRPC.grpc.Message getDefaultInstanceForType() {
      return com.msg_gRPC.grpc.Message.getDefaultInstance();
    }

    @java.lang.Override
    public com.msg_gRPC.grpc.Message build() {
      com.msg_gRPC.grpc.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.msg_gRPC.grpc.Message buildPartial() {
      com.msg_gRPC.grpc.Message result = new com.msg_gRPC.grpc.Message(this);
      result.expediteur_ = expediteur_;
      result.destinataire_ = destinataire_;
      result.contenu_ = contenu_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.msg_gRPC.grpc.Message) {
        return mergeFrom((com.msg_gRPC.grpc.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.msg_gRPC.grpc.Message other) {
      if (other == com.msg_gRPC.grpc.Message.getDefaultInstance()) return this;
      if (!other.getExpediteur().isEmpty()) {
        expediteur_ = other.expediteur_;
        onChanged();
      }
      if (!other.getDestinataire().isEmpty()) {
        destinataire_ = other.destinataire_;
        onChanged();
      }
      if (!other.getContenu().isEmpty()) {
        contenu_ = other.contenu_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.msg_gRPC.grpc.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.msg_gRPC.grpc.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object expediteur_ = "";
    /**
     * <code>string expediteur = 1;</code>
     */
    public java.lang.String getExpediteur() {
      java.lang.Object ref = expediteur_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expediteur_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string expediteur = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExpediteurBytes() {
      java.lang.Object ref = expediteur_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expediteur_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string expediteur = 1;</code>
     */
    public Builder setExpediteur(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      expediteur_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string expediteur = 1;</code>
     */
    public Builder clearExpediteur() {
      
      expediteur_ = getDefaultInstance().getExpediteur();
      onChanged();
      return this;
    }
    /**
     * <code>string expediteur = 1;</code>
     */
    public Builder setExpediteurBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      expediteur_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinataire_ = "";
    /**
     * <code>string destinataire = 2;</code>
     */
    public java.lang.String getDestinataire() {
      java.lang.Object ref = destinataire_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinataire_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destinataire = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDestinataireBytes() {
      java.lang.Object ref = destinataire_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinataire_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destinataire = 2;</code>
     */
    public Builder setDestinataire(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinataire_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destinataire = 2;</code>
     */
    public Builder clearDestinataire() {
      
      destinataire_ = getDefaultInstance().getDestinataire();
      onChanged();
      return this;
    }
    /**
     * <code>string destinataire = 2;</code>
     */
    public Builder setDestinataireBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinataire_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object contenu_ = "";
    /**
     * <code>string contenu = 3;</code>
     */
    public java.lang.String getContenu() {
      java.lang.Object ref = contenu_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contenu_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contenu = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContenuBytes() {
      java.lang.Object ref = contenu_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contenu_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contenu = 3;</code>
     */
    public Builder setContenu(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contenu_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contenu = 3;</code>
     */
    public Builder clearContenu() {
      
      contenu_ = getDefaultInstance().getContenu();
      onChanged();
      return this;
    }
    /**
     * <code>string contenu = 3;</code>
     */
    public Builder setContenuBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contenu_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gRPC.Message)
  }

  // @@protoc_insertion_point(class_scope:gRPC.Message)
  private static final com.msg_gRPC.grpc.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.msg_gRPC.grpc.Message();
  }

  public static com.msg_gRPC.grpc.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.msg_gRPC.grpc.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

