// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package com.msg_gRPC.grpc;

public final class Messaging {
  private Messaging() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gRPC_Message_descriptor;
  public static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gRPC_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gRPC_Confirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gRPC_Confirmation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gRPC_Utilisateur_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gRPC_Utilisateur_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gRPC_ListeMessages_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gRPC_ListeMessages_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017messaging.proto\022\004gRPC\"D\n\007Message\022\022\n\nex" +
      "pediteur\030\001 \001(\t\022\024\n\014destinataire\030\002 \001(\t\022\017\n\007" +
      "contenu\030\003 \001(\t\"8\n\014Confirmation\022\020\n\010reussit" +
      "e\030\001 \001(\010\022\026\n\016message_erreur\030\002 \001(\t\"&\n\013Utili" +
      "sateur\022\027\n\017nom_utilisateur\030\001 \001(\t\"0\n\rListe" +
      "Messages\022\037\n\010messages\030\001 \003(\0132\r.gRPC.Messag" +
      "e2\205\001\n\021ServiceMessagerie\0223\n\016EnvoyerMessag" +
      "e\022\r.gRPC.Message\032\022.gRPC.Confirmation\022;\n\021" +
      "RecupererMessages\022\021.gRPC.Utilisateur\032\023.g" +
      "RPC.ListeMessagesB\025\n\021com.msg_gRPC.grpcP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gRPC_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gRPC_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gRPC_Message_descriptor,
        new java.lang.String[] { "Expediteur", "Destinataire", "Contenu", });
    internal_static_gRPC_Confirmation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gRPC_Confirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gRPC_Confirmation_descriptor,
        new java.lang.String[] { "Reussite", "MessageErreur", });
    internal_static_gRPC_Utilisateur_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gRPC_Utilisateur_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gRPC_Utilisateur_descriptor,
        new java.lang.String[] { "NomUtilisateur", });
    internal_static_gRPC_ListeMessages_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gRPC_ListeMessages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gRPC_ListeMessages_descriptor,
        new java.lang.String[] { "Messages", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
