// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package com.msg_gRPC.grpc;

public interface UtilisateurOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gRPC.Utilisateur)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nom_utilisateur = 1;</code>
   */
  java.lang.String getNomUtilisateur();
  /**
   * <code>string nom_utilisateur = 1;</code>
   */
  com.google.protobuf.ByteString
      getNomUtilisateurBytes();
}
