// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package com.msg_gRPC.grpc;

public interface ListeMessagesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gRPC.ListeMessages)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .gRPC.Message messages = 1;</code>
   */
  java.util.List<com.msg_gRPC.grpc.Message> 
      getMessagesList();
  /**
   * <code>repeated .gRPC.Message messages = 1;</code>
   */
  com.msg_gRPC.grpc.Message getMessages(int index);
  /**
   * <code>repeated .gRPC.Message messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .gRPC.Message messages = 1;</code>
   */
  java.util.List<? extends com.msg_gRPC.grpc.MessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .gRPC.Message messages = 1;</code>
   */
  com.msg_gRPC.grpc.MessageOrBuilder getMessagesOrBuilder(
      int index);
}
