// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package com.msg_gRPC.grpc;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gRPC.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string expediteur = 1;</code>
   */
  java.lang.String getExpediteur();
  /**
   * <code>string expediteur = 1;</code>
   */
  com.google.protobuf.ByteString
      getExpediteurBytes();

  /**
   * <code>string destinataire = 2;</code>
   */
  java.lang.String getDestinataire();
  /**
   * <code>string destinataire = 2;</code>
   */
  com.google.protobuf.ByteString
      getDestinataireBytes();

  /**
   * <code>string contenu = 3;</code>
   */
  java.lang.String getContenu();
  /**
   * <code>string contenu = 3;</code>
   */
  com.google.protobuf.ByteString
      getContenuBytes();
}
